// react/plugin/src/PodW.jsx
import { useEffect } from "react";

function PodW({ apikey, debug }) {
  useEffect(() => {
    const script = document.createElement('script')
    script.src = "https://podmind.voxgig.com/widget/voxgig-podmind-ask.js"
    return () => document.head.appendChild(script)
  }, [])

  return (
    <voxgig-podmind-ask
      apikey={apikey}
      debug={debug}
    >
    </voxgig-podmind-ask>
  )
}

export default PodW;

// nuxt/plugin/src/PodW.vue
<template>
  <voxgig-podmind-ask apikey="your-api-key" debug="true">
  </voxgig-podmind-ask>
</template>



<script>
export default defineNuxtComponent({
  name: 'PodW',
  head: {
    script: [
      {
        hid: 'podw-script',
        async: true,
        src: 'https://podmind.voxgig.com/widget/voxgig-podmind-ask.js'
      }
    ]
  }
})
</script>
