// gatsby/plugin/src/PodW.jsx
import { Script } from "gatsby"

export default function PodW({ apikey, debug }) {
  return (
    <>
      <Script async src="https://podmind.voxgig.com/widget/voxgig-podmind-ask.js" />

      <voxgig-podmind-ask
        apikey={apikey}
        debug={debug}
      >
      </voxgig-podmind-ask>
    </>
  );
}

// nuxt/plugin/src/PodW.vue
<template>
  <voxgig-podmind-ask apikey="your-api-key" debug="true">
  </voxgig-podmind-ask>
</template>



<script>
export default defineNuxtComponent({
  name: 'PodW',
  head: {
    script: [
      {
        hid: 'podw-script',
        async: true,
        src: 'https://podmind.voxgig.com/widget/voxgig-podmind-ask.js'
      }
    ]
  }
})
</script>
